apiVersion: v1
kind: Pod
metadata:
  name: pod-name
  namespace: default
spec:
  labels:
    app: nginx
  containers:
  - name: nginx-container
    image: nginx:latest
    ports:
    - containerPort: 80