apiVersion: app/v1
kind: ReplicaSet
metadata:
  name: ticktawebcapp-replicaset
  namespace: dev
  labels:
    app: ticktacapp
spec:
  replicas: 10
  selector:
    matchLabels:
      app: ticktacapp
  template:
    metadata:
      labels:
        app: ticktacapp
    spec:
      containers:
      - name: ticktawebcapp-container
        image: dinvar/dinvardevopsrepo:v1.3
        ports:
        - containerPort: 80