apiVersion: v1
kind: Service
metadata:
  name: ticktawebcapp-service
  namespace: dev
spec:
  selector:
    app: ticktacapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP