apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: python-read-only-binding-pods
  namespace: dev
subjects:
- kind: ServiceAccount
  name: python-service-account
  namespace: dev
roleRef:
  kind: Role
  name: python-role
  apiGroup: rbac.authorization.k8s.io
