apiVersion: apps/v1
kind: Deployment
metadata:
  name: tic-tac-blue-deployment
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: tic-tac-app
      version: blue
  template:
    metadata:
      labels:
        app: tic-tac-app
        version: blue
    spec:
      containers:
        - name: tic-tac-container
          image: dinvar/test-repo:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
