apiVersion: v1
kind: Service
metadata:
  name: tic-tac-green-service
spec:
  type: NodePort
  selector:
    app: tic-tac-app
    version: green
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30081
