apiVersion: apps/v1
kind: Deployment
metadata:
  name: tictac-app
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tictac
  template:
    metadata:
      labels:
        app: tictac
    spec:
      imagePullSecrets:
        - name: ecr-secret
      containers:
      - name: tictac
        image: dilipopseng/tictac:24
        imagePullPolicy: Always
        ports:
        - containerPort: 80

        ###
